### ISSUE TITLE
compilation fails caused by missing ui element

### ISSUE THREAD

**Issue by eworm-de** [Yubico/yubikey-personalization-gui#22]
Compilation fails with the following error message:

src/ui/toolpage.cpp: In constructor ‘ToolPage::ToolPage(QWidget*)’:
src/ui/toolpage.cpp:85:9: error: ‘class Ui::ToolPage’ has no member named ‘importBox’
     ui->importBox->setVisible(false);

This is caused by commit c26d5d67e3aa44ec9fc893888dde14b1c14a302b (drop box around import).
